export default {
  SET_CALL_STATE: 'SET_CALL_STATE',
  SET_ACTIVE_PHONE_NUMBER: 'SET_ACTIVE_PHONE_NUMBER',
  SET_IS_ACCOUNT_CALL_IN_PROGRESS: 'SET_IS_ACCOUNT_CALL_IN_PROGRESS',
  SET_IS_CALL_IN_PROGRESS: 'SET_IS_CALL_IN_PROGRESS',
};
