export default {
  USER_ID_KEY: 'USER_ID_KEY',
  TOKEN_KEY: 'TOKEN_KEY',
  REFRESH_TOKEN_KEY: 'REFRESH_TOKEN_KEY',
  PHONE_NUMBER_KEY: 'PHONE_NUMBER_KEY',
  ACCOUNT_ID_KEY: 'ACCOUNT_ID_KEY',
  IS_ACTIVE_KEY: 'IS_ACTIVE_KEY',
  PRIVATE_KEY_KEY: 'PRIVATE_KEY_KEY',
};
