export default {
  SET_USER_ID: 'SET_USER_ID',
  SET_USER_NAME: 'SET_USER_NAME',
  SET_TOKEN: 'SET_TOKEN',
  SET_PHONE_NUMBER: 'SET_PHONE_NUMBER',
  SET_ACCOUNT_ID: 'SET_ACCOUNT_ID',
  SET_IS_ACTIVE: 'SET_IS_ACTIVE',
};
