const APP_NAME = 'A Number For Us';

export default {
  APP_NAME,
  TITLE_APP_NAME: APP_NAME,
  TITLE_LANDING: APP_NAME,
  TITLE_CALLS: 'Calls',
  TITLE_CHATS: 'Messages',
  TITLE_CREATE_CHAT: 'New Message',
  TITLE_CREATE_CALL: 'New Call',
  TITLE_CONTACTS: 'Contacts',
  TITLE_LOGOUT: 'Logout',
  TITLE_AVAILABLE_NUMBER: 'Reserve Your Number',
  TITLE_ENTER_CODE: 'Scan Invitation',
  TITLE_MEMBERS: 'Us',
  TITLE_SHARE_CODE: 'Complete Enrollment',
  TITLE_MANAGE: 'Manage',
  TITLE_INVITE: 'Invite',
  LABEL_LOGIN: 'Login',
  ERROR_REQUEST_TITLE: '🙄',
  ERROR_REQUEST_MESSAGE: `Please verify you are connected to the internet and try again`,
  LABEL_OKAY: 'Okay',
  LABEL_JOIN_LINE: 'Join A Number',
  LABEL_CREATE_LINE: 'Reserve Your Number',
  LABEL_HAVE_LINE: 'We Already Have A Number',
  LABEL_DONT_HAVE_LINE: 'You don\'t have a number!',
  LABEL_CANCEL: 'Cancel',
  LABEL_RETRY: 'Retry',
  LABEL_EXIT_SETUP: 'Exit',
  LABEL_CHAT_EMPTY_PRIMARY: 'Welcome',
  LABEL_CHAT_EMPTY_SECONDARY: 'Hold to copy your number',
  LABEL_AVAILABLE_NUMBER_EMPTY_PRIMARY: '',
  CONFIRM_PURCHASE_TITLE: 'Continue?',
  CONFIRM_PURCHASE_MESSAGE: 'Do you wish to join?',
  CONFIRM_PURCHASE_AFFIRMATIVE: 'Yes',
  CONFIRM_PURCHASE_NEGATIVE: 'No',
  CONGRATULATIONS_TITLE: 'Congratulations! 🎉🎉🎉',
  CONGRATULATIONS_MESSAGE: 'It\'s official! You\'re sharing a number! Copy your number and share it!',
  LABEL_LEAVE_LINE: 'Leave Number',
  LEAVE_LINE_TITLE: 'Leave Number?',
  LEAVE_LINE_MESSAGE: 'You are about to leave the number and will no longer have access. ' +
  'Your partner will be notified of your decision to leave. ' +
  'If you are the last person on the number, the number will be scheduled for removal. ' +
  'Do you wish to continue?',
  LEAVE_LINE_AFFIRMATIVE: 'Yes, remove me',
  LABEL_COPY_NUMBER: 'Copy now',
  LABEL_MAYBE_LATER: 'Maybe later',
  LABEL_ACTIVATE: 'To complete enrollment, invite others to your number',
  LABEL_INVITE: 'Invite others to your number',
  LABEL_JOIN_ME: `Follow this link to join our number on ${APP_NAME}`,
  LABEL_COPY_LINK: 'Copy link',
  LABEL_SHARE_LINK: 'Share link',
  LABEL_QR_CODE: 'QR code',
  LABEL_QR_CODE_SCAN: 'If shared with another, they can scan it with Join A Number',
  LABEL_RESEND_EMAIL_TITLE: 'Verify email',
  LABEL_RESEND_EMAIL_MESSAGE: 'Please verify email address to reserve a number.',
  LABEL_RESEND: 'Resend verification email',
  LABEL_RESEND_EMAIL_SUCCESS_TITLE: 'Success!',
  LABEL_RESEND_EMAIL_SUCCESS_MESSAGE: 'Look for the verification email in your inbox and click the link in that email.',
  LABEL_ACTIVITY_SHARE_TITLE: `Will you join me on ${APP_NAME}?`,
};
