const APP_NAME = 'Bubblepop';

export default {
  APP_NAME,
  TITLE_APP_NAME: APP_NAME,
  TITLE_LANDING: APP_NAME,
  TITLE_CHATS: 'Messages',
  TITLE_CALLS: 'Calls',
  TITLE_LOGOUT: 'Logout',
  TITLE_AVAILABLE_NUMBER: 'Select Your Number',
  TITLE_LANDING_TWO: 'Getting Started',
  TITLE_ENTER_LINE: 'Enter Line Number',
  TITLE_ENTER_CODE: 'Enter Code',
  TITLE_MEMBERS: 'Us',
  TITLE_SHARE_CODE: 'Invite',
  LABEL_NEXT: 'Next',
  LABEL_LOGIN: 'Login',
  LABEL_GETTING_STARTED: 'Get Started',
  LABEL_APP_SLOGAN: 'Your relationship needs a number',
  LABEL_LOCATION_PERMISSION_TITLE: 'Location Permission Requested',
  LABEL_LOCATION_PERMISSION_MESSAGE: `${APP_NAME} needs access to your location to help find a local phone number`,
  LABEL_OKAY: 'Okay',
  LABEL_JOIN_LINE: 'Join Line',
  LABEL_CREATE_LINE: 'New Line',
  HINT_PHONE_NUMBER: '+1 312-815-1987',
  HINT_CODE: '0811',
  LABEL_CONFIRM: 'Confirm',
  LABEL_NEXT: 'Next',
  LABEL_CANCEL: 'Cancel',
  WARNING_PHONE_NUMBER_REQUIRED: 'Please enter a phone number to join',
  WARNING_CODE_REQUIRED: 'Please enter a valid code',
  ALERT_SUBSCRIPTION_TITLE: 'Subscribe to join',
  ALERT_SUBSCRIPTION_MESSAGE: 'To join, your account will be billed $0.99 a month.',
  LABEL_CHAT_EMPTY_PRIMARY: 'Looks quiet',
  LABEL_AVAILABLE_NUMBER_EMPTY_PRIMARY: '',
};
