const APP_NAME = 'Promise';

export default {
  APP_NAME,
  TITLE_APP_NAME: APP_NAME,
  TITLE_LANDING: APP_NAME,
  TITLE_CHATS: 'Messages',
  TITLE_CALLS: 'Calls',
  TITLE_LOGOUT: 'Logout',
  TITLE_AVAILABLE_NUMBER: 'Select Number',
  TITLE_LANDING_TWO: 'Getting Started',
  TITLE_ENTER_CODE: 'Scan Proposal',
  TITLE_MEMBERS: 'Us',
  TITLE_SHARE_CODE: 'Propose',
  TITLE_MANAGE_SUBSCRIPTION: 'Manage',
  LABEL_LOGIN: 'Login',
  LABEL_GETTING_STARTED: 'Get Started',
  LABEL_APP_SLOGAN: 'A Number For Us',
  LABEL_LANDING_TWO: 'Let\'s Get Started',
  ERROR_REQUEST_TITLE: 'Request failed',
  ERROR_REQUEST_MESSAGE: `Please verify you are connected to the internet and try again`,
  LABEL_OKAY: 'Okay',
  LABEL_JOIN_LINE: 'Join Existing Number',
  LABEL_CREATE_LINE: 'Create New Number',
  LABEL_CANCEL: 'Cancel',
  LABEL_CHAT_EMPTY_PRIMARY: 'Looks quiet',
  LABEL_CHAT_EMPTY_SECONDARY: 'Hold to copy your number',
  LABEL_AVAILABLE_NUMBER_EMPTY_PRIMARY: '',
};
